language: csharp
solution: ./LoggingServices.sln
sudo: required

install:
  - sudo apt-get install nunit-console
  - nuget restore ./LoggingServices.sln

script:
  - xbuild ./LoggingServices.sln
  - nunit-console ./tests/LoggingServices.Tests/bin/Debug/LoggingServices.Tests.dll